# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: your-spotify 
spec:
  selector:
    app: your-spotify
  type: ClusterIP
  ports:
    - name: server
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
---
