libreddit:
  image:
    registry: quay.io
    repository: redlib/redlib
    tag: latest
  
  env:
    - name: LIBREDDIT_DEFAULT_SHOW_NSFW
      value: "on"
    - name: LIBREDDIT_DEFAULT_THEME
      value: "dracula"
