---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: plex-svc
spec:
  selector:
    app: plex
  ports:
    - protocol: TCP
      port: 32400
      targetPort: 32400
      name: pms-tcp
    - protocol: UDP
      port: 32400
      targetPort: 32400
      name: pms-udp
    - protocol: TCP
      port: 3005
      targetPort: 3005
      name: companion
    - protocol: TCP
      port: 8324
      targetPort: 8324
      name: roku
    - protocol: UDP
      port: 1900
      targetPort: 1900
      name: dlna0
    - protocol: TCP
      port: 32469
      targetPort: 32469
      name: dlna1
    - protocol: UDP
      port: 32410
      targetPort: 32410
      name: gdm0
    - protocol: UDP
      port: 32412
      targetPort: 32412
      name: gdm1
    - protocol: UDP
      port: 32413
      targetPort: 32413
      name: gdm2
    - protocol: UDP
      port: 32414
      targetPort: 32414
      name: gdm3
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.plex.loadBalancerIP }}
