plex:  
  env:
    - name: TZ
      value: America/Vancouver
    - name: PLEX_CLAIM
      valueFrom:
        secretKeyRef:
          name: plex-claim
          key: token
    - name: VERSION
      value: docker

  # Set a static IP so that Plex knows where to find itself.
  # This fixes Plex showing up as 'Remote' when it should be 'Local'
  loadBalancerIP: 10.5.51.2

  dataStorage:
    storageClass: local-retain-data0 # provision on /mnt/data0

  volumes:
    - name: audio
      nfs:
        server: k8s-nas
        path: /media/audio
        readOnly: true
    - name: photo
      nfs:
        server: k8s-nas
        path: /media/photo
        readOnly: true
    - name: video
      nfs:
        server: k8s-nas
        path: /media/video
        readOnly: true

  volumeMounts:
    - name: audio
      mountPath: /data-audio
    - name: photo
      mountPath: /data-photo
    - name: video
      mountPath: /data
    - name: gdrive-vdisk1
      mountPath: /data-gvdisk1
      subPath: media
    - name: crypt-media
      mountPath: /svideo
      subPath: videos
    - name: crypt-media
      mountPath: /simg
      subPath: images

  volumeClaims:
    - metadata:
        name: crypt-media
      spec:
        storageClassName: smb-crypt-media
        accessModes:
        - ReadOnlyMany
        resources:
          requests:
            storage: 1Ki
    - metadata:
        name: gdrive-vdisk1
      spec:
        storageClassName: smb-gdrive-vdisk1
        accessModes:
        - ReadOnlyMany
        resources:
          requests:
            storage: 1Ki

  # Restrict to only `k8s1` (for PVC)
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s1
