audiobookshelf:
  dataStorage:
    storageClass: local-path-retain   

  volumes:
    - name: books
      nfs:
        server: 10.5.50.14
        path: /media/books
        readOnly: true

    - name: audiobooks
      nfs:
        server: 10.5.50.14
        path: /media/audio/audiobooks
        readOnly: true

  volumeMounts:
    - name: books
      mountPath: /books
    - name: audiobooks
      mountPath: /audiobooks

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    className: nginx
    
    host: books.cloud.browningluke.dev
    tls:
      - hosts:
        - books.cloud.browningluke.dev
        secretName: audiobookshelf-cert

  # Restrict to only `k8s1` (for local-path PVC)
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s1
