persistence:
  enabled: true
  storageClass: longhorn-retain
  size: 1Gi

backup:
  enabled: true
  storageClass: nfs-backups
  storage: 500Mi # Not respected by the nfs csi driver

extraVolumes:
  - name: books
    nfs:
      server: 10.5.50.14
      path: /media/books
      readOnly: true

  - name: audiobooks
    nfs:
      server: 10.5.50.14
      path: /media/audio/audiobooks
      readOnly: true

volumeMounts:
  - name: books
    mountPath: /books
  - name: audiobooks
    mountPath: /audiobooks

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  className: nginx
  
  host: books.cloud.browningluke.dev
  tls:
    - hosts:
      - books.cloud.browningluke.dev
      secretName: audiobookshelf-cert
