# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .Values.audiobookshelf.ingress.annotations | nindent 4 }}
  name: audiobookshelf
spec:
  ingressClassName: {{ .Values.audiobookshelf.ingress.className }}
  rules:
    - host: {{ .Values.audiobookshelf.ingress.host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: audiobookshelf
              port:
                number: 80
  tls:
    {{- toYaml .Values.audiobookshelf.ingress.tls | nindent 4 }}
---
