# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf 
spec:
  selector:
    app: audiobookshelf
  type: ClusterIP
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: 80
---
