# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  serviceName: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- toYaml .Values.extraEnv | nindent 12 }}
          lifecycle:
          {{- toYaml .Values.lifecycle | nindent 12 }}
          ports:
            - containerPort: 80
              name: app
          resources: {{ toYaml .Values.resources | nindent 12}}
          livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 12 }}
            - name: {{ .Chart.Name }}-data
              mountPath: {{ .Values.persistence.config.mountPath }}
              subPath: {{ .Values.persistence.config.subPath }}
            - name: {{ .Chart.Name }}-data
              mountPath: {{ .Values.persistence.metadata.mountPath }}
              subPath: {{ .Values.persistence.metadata.subPath }}
          {{- if .Values.backup.enabled }}
            - name: {{ .Chart.Name }}-backups
              mountPath: {{ .Values.backup.mountPath }}
              subPath: {{ .Values.backup.subPath }}
          {{- end }}
      volumes:
      {{- toYaml .Values.extraVolumes | nindent 8 }}
      affinity:
      {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
      {{- toYaml .Values.tolerations | nindent 8 }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Chart.Name }}-data
      annotations:
        {{ .Values.persistence.annotations | toYaml | nindent 8 }}
      labels:
        {{ .Values.persistence.labels | toYaml | nindent 8 }}
    spec:
      storageClassName: {{ .Values.persistence.storageClass }}
      accessModes:
        {{- range .Values.persistence.accessModes }}
        - {{ . | quote }}
        {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- if .Values.backup.enabled }}
  - metadata:
      name: {{ .Chart.Name }}-backups
      annotations:
        {{ .Values.backup.annotations | toYaml | nindent 8 }}
      labels:
        {{ .Values.backup.labels | toYaml | nindent 8 }}
    spec:
      storageClassName: {{ .Values.backup.storageClass }}
      accessModes:
        {{- range .Values.backup.accessModes }}
        - {{ . | quote }}
        {{- end }}
      resources:
        requests:
          storage: {{ .Values.backup.size }}
  {{- end }}
---
