# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: audiobookshelf
spec:
  selector:
    matchLabels:
      app: audiobookshelf
  serviceName: "audiobookshelf"
  replicas: 1
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: audiobookshelf
          image: {{ .Values.audiobookshelf.image.registry }}/{{ .Values.audiobookshelf.image.repository }}:{{ .Values.audiobookshelf.image.tag }}
          ports:
            - containerPort: 80
              name: app
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          volumeMounts:
          {{- toYaml .Values.audiobookshelf.volumeMounts | nindent 12 }}
            - name: audiobookshelf-data
              mountPath: /config
              subPath: config
            - name: audiobookshelf-data
              mountPath: /metadata
              subPath: metadata
      volumes:
      {{- toYaml .Values.audiobookshelf.volumes | nindent 8 }}
      affinity:
      {{- toYaml .Values.audiobookshelf.affinity | nindent 8 }}
  volumeClaimTemplates:
  - metadata:
      name: audiobookshelf-data
      annotations:
        volumeType: local
    spec:
      storageClassName: {{ .Values.audiobookshelf.dataStorage.storageClass }}
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.audiobookshelf.dataStorage.size }}
---
