# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: libreddit
spec:
  selector:
    app: libreddit
  type: ClusterIP
  ports:
  - name: libreddit
    protocol: TCP
    port: 80
    targetPort: 8080
---
