# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  rimgo
  labels:
    app: rimgo
spec:
  selector:
    matchLabels:
      app: rimgo
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rimgo
    spec:
      containers:
        - name: rimgo
          image: {{ .Values.rimgo.image.registry }}/{{ .Values.rimgo.image.repository }}:{{ .Values.rimgo.image.tag }}
          env:
          {{- toYaml .Values.rimgo.env | nindent 12 }}
            - name: ADDRESS
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 8080
              name: app
          # resources:
          #   requests:
          #     cpu: 50m
          #     memory: 50Mi
          #   limits:
          #     cpu: 250m
          #     memory: 200Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
      restartPolicy: Always
      tolerations:
        - key: kubernetes.io/arch
          operator: Equal
          value: arm64
          effect: NoSchedule
---
