# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: rimgo
spec:
  selector:
    app: rimgo
  type: ClusterIP
  ports:
  - name: rimgo
    protocol: TCP
    port: 80
    targetPort: 3000
---
